using Microsoft.EntityFrameworkCore;using Microsoft.Extensions.DependencyInjection;using MyFundex.BuildingBlocks.Abstractions;using MyFundex.BuildingBlocks.Domain;using MyFundex.BuildingBlocks.Persistence;using MyFundex.BuildingBlocks.Results;using MyFundex.Contracts;
namespace MyFundex.Trading;
public sealed class Order:EntityBase{public Guid OrderId{get;set;}public Guid AccountId{get;set;}public long FundedAccountInternalId{get;set;}public string InstrumentToken{get;set;}="";public string Symbol{get;set;}="";public string Side{get;set;}="BUY";public string OrderType{get;set;}="MARKET";public decimal Quantity{get;set;}public decimal? RequestedPrice{get;set;}public decimal EstimatedPrice{get;set;}public decimal FilledQuantity{get;set;}public decimal? AverageFillPrice{get;set;}public string Status{get;set;}="Requested";public string? BrokerOrderId{get;set;}public Guid IdempotencyKey{get;set;}public Guid CorrelationId{get;set;}public DateTimeOffset? PlacedAt{get;set;}public DateTimeOffset? CompletedAt{get;set;}}
public sealed class OrderEvent:EntityBase{public Guid OrderEventId{get;set;}public long OrderInternalId{get;set;}public string EventType{get;set;}="";public string? OldStatus{get;set;}public string NewStatus{get;set;}="";public string? ProviderPayload{get;set;}public DateTimeOffset OccurredAt{get;set;}=DateTimeOffset.UtcNow;}
public sealed class Execution:EntityBase{public Guid ExecutionId{get;set;}public long OrderInternalId{get;set;}public string? BrokerExecutionId{get;set;}public decimal Quantity{get;set;}public decimal Price{get;set;}public decimal GrossValue{get;set;}public DateTimeOffset ExecutedAt{get;set;}}
public sealed class TradingDbContext(DbContextOptions<TradingDbContext> o,ICurrentActor a):AuditableDbContext(o,a){public DbSet<Order>Orders=>Set<Order>();public DbSet<OrderEvent>OrderEvents=>Set<OrderEvent>();public DbSet<Execution>Executions=>Set<Execution>();protected override void OnModelCreating(ModelBuilder m) => ConfigureModel(m); public static void ConfigureModel(ModelBuilder m) {m.HasDefaultSchema("trading");ConfigureEntity(m.Entity<Order>());ConfigureEntity(m.Entity<OrderEvent>());ConfigureEntity(m.Entity<Execution>());m.Entity<Order>().HasIndex(x=>x.OrderId).IsUnique();m.Entity<Order>().HasIndex(x=>x.IdempotencyKey).IsUnique();m.Entity<Order>().HasIndex(x=>new{x.FundedAccountInternalId,x.CreatedAt});m.Entity<Order>().Property(x=>x.Quantity).HasPrecision(20,6);m.Entity<Order>().Property(x=>x.EstimatedPrice).HasPrecision(20,6);}}
public sealed record PlaceOrderCommand(Guid AccountId,string InstrumentToken,string Symbol,string Side,string OrderType,decimal Quantity,decimal? Price,Guid IdempotencyKey);
public sealed record PlaceOrderResult(Guid OrderId,string Status,string? BrokerOrderId);
public static class TradingModule{public static IServiceCollection AddTradingModule(this IServiceCollection s,string cs){s.AddDbContext<TradingDbContext>(o=>o.UseNpgsql(cs));s.AddScoped<OrderService>();return s;}}
