using Microsoft.EntityFrameworkCore;using Microsoft.Extensions.DependencyInjection;using MyFundex.BuildingBlocks.Abstractions;using MyFundex.BuildingBlocks.Domain;using MyFundex.BuildingBlocks.Persistence;using MyFundex.Contracts;
namespace MyFundex.FundedAccounts;
public sealed class FundedAccount:EntityBase{public Guid AccountId{get;set;}public long UserInternalId{get;set;}public long SubscriptionInternalId{get;set;}public string AccountNumber{get;set;}="";public string Status{get;set;}="Active";public decimal FundedCapital{get;set;}public decimal WalletContribution{get;set;}public decimal CurrentBuyingPower{get;set;}public string CurrencyCode{get;set;}="INR";public Guid? ActivePolicyAssignmentId{get;set;}public DateTimeOffset? ActivatedAt{get;set;}public DateTimeOffset? SuspendedAt{get;set;}public DateTimeOffset? ClosedAt{get;set;}}
public sealed class CapitalAllocation:EntityBase{public Guid AllocationId{get;set;}public long FundedAccountInternalId{get;set;}public string AllocationType{get;set;}="InitialFunding";public decimal Amount{get;set;}public DateTimeOffset EffectiveAt{get;set;}public string? ReferenceType{get;set;}public string? ReferenceId{get;set;}}
public sealed class AccountStatusHistory:EntityBase{public Guid StatusHistoryId{get;set;}public long FundedAccountInternalId{get;set;}public string? FromStatus{get;set;}public string ToStatus{get;set;}="";public string? ReasonCode{get;set;}public string? Reason{get;set;}public DateTimeOffset ChangedAt{get;set;}}
public sealed class AccountsDbContext(DbContextOptions<AccountsDbContext> o,ICurrentActor a):AuditableDbContext(o,a){public DbSet<FundedAccount>Accounts=>Set<FundedAccount>();public DbSet<CapitalAllocation>CapitalAllocations=>Set<CapitalAllocation>();public DbSet<AccountStatusHistory>StatusHistory=>Set<AccountStatusHistory>();protected override void OnModelCreating(ModelBuilder m){m.HasDefaultSchema("accounts");ConfigureEntity(m.Entity<FundedAccount>());ConfigureEntity(m.Entity<CapitalAllocation>());ConfigureEntity(m.Entity<AccountStatusHistory>());m.Entity<FundedAccount>().HasIndex(x=>x.AccountId).IsUnique();m.Entity<FundedAccount>().HasIndex(x=>x.AccountNumber).IsUnique().HasFilter("is_deleted=false");m.Entity<FundedAccount>().Property(x=>x.FundedCapital).HasPrecision(20,4);m.Entity<FundedAccount>().Property(x=>x.CurrentBuyingPower).HasPrecision(20,4);}}
public sealed class AccountService(AccountsDbContext db):IFundedAccountReader,IFundedAccountCapitalService{
 public async Task<FundedAccountSnapshot?> GetByPublicIdAsync(Guid id,CancellationToken ct)=>await db.Accounts.AsNoTracking().Where(x=>x.AccountId==id).Select(x=>new FundedAccountSnapshot(x.Id,x.AccountId,x.UserInternalId,x.FundedCapital,x.CurrentBuyingPower,x.Status,x.Version)).SingleOrDefaultAsync(ct);
 public async Task<bool> TryReserveAsync(long id,decimal amount,long version,CancellationToken ct){var rows=await db.Accounts.Where(x=>x.Id==id&&x.Version==version&&x.CurrentBuyingPower>=amount&&x.Status=="Active").ExecuteUpdateAsync(s=>s.SetProperty(x=>x.CurrentBuyingPower,x=>x.CurrentBuyingPower-amount).SetProperty(x=>x.Version,x=>x.Version+1).SetProperty(x=>x.UpdatedAt,DateTimeOffset.UtcNow),ct);return rows==1;}
 public Task ReleaseAsync(long id,decimal amount,CancellationToken ct)=>db.Accounts.Where(x=>x.Id==id).ExecuteUpdateAsync(s=>s.SetProperty(x=>x.CurrentBuyingPower,x=>x.CurrentBuyingPower+amount).SetProperty(x=>x.Version,x=>x.Version+1),ct);
}
public static class FundedAccountsModule{public static IServiceCollection AddFundedAccountsModule(this IServiceCollection s,string cs){s.AddDbContext<AccountsDbContext>(o=>o.UseNpgsql(cs));s.AddScoped<AccountService>();s.AddScoped<IFundedAccountReader>(sp=>sp.GetRequiredService<AccountService>());s.AddScoped<IFundedAccountCapitalService>(sp=>sp.GetRequiredService<AccountService>());return s;}}
