START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM fundex_integration."__EFMigrationsHistory" WHERE "MigrationId" = '20260930195238_CompleteTradingLifecycle') THEN
        IF NOT EXISTS(SELECT 1 FROM pg_namespace WHERE nspname = 'myfund_prod_trading') THEN
            CREATE SCHEMA myfund_prod_trading;
        END IF;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM fundex_integration."__EFMigrationsHistory" WHERE "MigrationId" = '20260930195238_CompleteTradingLifecycle') THEN
        IF NOT EXISTS(SELECT 1 FROM pg_namespace WHERE nspname = 'myfund_sandbox_trading') THEN
            CREATE SCHEMA myfund_sandbox_trading;
        END IF;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM fundex_integration."__EFMigrationsHistory" WHERE "MigrationId" = '20260930195238_CompleteTradingLifecycle') THEN
        IF NOT EXISTS(SELECT 1 FROM pg_namespace WHERE nspname = 'myfund_prod_wallet') THEN
            CREATE SCHEMA myfund_prod_wallet;
        END IF;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM fundex_integration."__EFMigrationsHistory" WHERE "MigrationId" = '20260930195238_CompleteTradingLifecycle') THEN
    ALTER TABLE fundex_withdrawal."Requests" ADD "BeneficiaryReference" text;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM fundex_integration."__EFMigrationsHistory" WHERE "MigrationId" = '20260930195238_CompleteTradingLifecycle') THEN
    ALTER TABLE fundex_withdrawal."Requests" ADD "PayoutStartedAt" timestamp with time zone;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM fundex_integration."__EFMigrationsHistory" WHERE "MigrationId" = '20260930195238_CompleteTradingLifecycle') THEN
    ALTER TABLE fundex_withdrawal."Requests" ADD "ProviderPayoutId" text;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM fundex_integration."__EFMigrationsHistory" WHERE "MigrationId" = '20260930195238_CompleteTradingLifecycle') THEN
    ALTER TABLE fundex_withdrawal."Requests" ADD "UserInternalId" bigint NOT NULL DEFAULT 0;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM fundex_integration."__EFMigrationsHistory" WHERE "MigrationId" = '20260930195238_CompleteTradingLifecycle') THEN
    ALTER TABLE fundex_subscription."PlanVersions" ADD "FundedDailyLossPercent" numeric(20,4) NOT NULL DEFAULT 5.0;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM fundex_integration."__EFMigrationsHistory" WHERE "MigrationId" = '20260930195238_CompleteTradingLifecycle') THEN
    ALTER TABLE fundex_subscription."PlanVersions" ADD "FundedTotalLossPercent" numeric(20,4) NOT NULL DEFAULT 10.0;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM fundex_integration."__EFMigrationsHistory" WHERE "MigrationId" = '20260930195238_CompleteTradingLifecycle') THEN
    ALTER TABLE fundex_trading."Orders" ADD "IsLiquidation" boolean NOT NULL DEFAULT FALSE;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM fundex_integration."__EFMigrationsHistory" WHERE "MigrationId" = '20260930195238_CompleteTradingLifecycle') THEN
    ALTER TABLE fundex_trading."Orders" ADD "ReservedCash" numeric(20,4) NOT NULL DEFAULT 0.0;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM fundex_integration."__EFMigrationsHistory" WHERE "MigrationId" = '20260930195238_CompleteTradingLifecycle') THEN
    ALTER TABLE fundex_trading."Orders" ADD "UsesLiveBook" boolean NOT NULL DEFAULT FALSE;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM fundex_integration."__EFMigrationsHistory" WHERE "MigrationId" = '20260930195238_CompleteTradingLifecycle') THEN
    ALTER TABLE fundex_wallet."Entries" ADD "LedgerAccount" text NOT NULL DEFAULT 'TraderPayable';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM fundex_integration."__EFMigrationsHistory" WHERE "MigrationId" = '20260930195238_CompleteTradingLifecycle') THEN
    ALTER TABLE fundex_accounts."Accounts" ADD "BrokerUserId" text;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM fundex_integration."__EFMigrationsHistory" WHERE "MigrationId" = '20260930195238_CompleteTradingLifecycle') THEN
    CREATE TABLE myfund_prod_trading."Books" (
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "AccountId" uuid NOT NULL,
        "Equity" numeric(20,4) NOT NULL,
        "DayOpeningEquity" numeric(20,4) NOT NULL,
        "TradingDate" date NOT NULL,
        "ValuedAt" timestamp with time zone,
        "CloseRequestId" uuid,
        "CloseReason" text,
        "Cash" numeric(20,4) NOT NULL,
        "ReservedCash" numeric(20,4) NOT NULL,
        "RealizedProfit" numeric(20,4) NOT NULL,
        "Status" text NOT NULL,
        "CreatedAt" timestamptz NOT NULL,
        "CreatedBy" bigint NOT NULL,
        "UpdatedAt" timestamptz,
        "UpdatedBy" bigint,
        "DeletedAt" timestamptz,
        "DeletedBy" bigint,
        "IsDeleted" boolean NOT NULL,
        "Version" bigint NOT NULL,
        CONSTRAINT "PK_Books" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM fundex_integration."__EFMigrationsHistory" WHERE "MigrationId" = '20260930195238_CompleteTradingLifecycle') THEN
    CREATE TABLE myfund_sandbox_trading."Books" (
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "AccountInternalId" bigint NOT NULL,
        "AccountId" uuid NOT NULL,
        "ReservedCash" numeric(20,4) NOT NULL,
        "Cash" numeric(20,4) NOT NULL,
        "Equity" numeric(20,4) NOT NULL,
        "RealizedProfit" numeric(20,4) NOT NULL,
        "DayOpeningEquity" numeric(20,4) NOT NULL,
        "TradingDate" date NOT NULL,
        "TradingDays" integer NOT NULL,
        "LastTradeDate" date,
        "Status" text NOT NULL,
        "ValuedAt" timestamp with time zone NOT NULL,
        "CreatedAt" timestamptz NOT NULL,
        "CreatedBy" bigint NOT NULL,
        "UpdatedAt" timestamptz,
        "UpdatedBy" bigint,
        "DeletedAt" timestamptz,
        "DeletedBy" bigint,
        "IsDeleted" boolean NOT NULL,
        "Version" bigint NOT NULL,
        CONSTRAINT "PK_Books" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM fundex_integration."__EFMigrationsHistory" WHERE "MigrationId" = '20260930195238_CompleteTradingLifecycle') THEN
    CREATE TABLE fundex_subscription."ChallengeNotices" (
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "NoticeId" uuid NOT NULL,
        "UserInternalId" bigint NOT NULL,
        "SubscriptionInternalId" bigint NOT NULL,
        "Outcome" text NOT NULL,
        "DeliveredAt" timestamp with time zone,
        "LeaseUntil" timestamp with time zone,
        "Attempts" integer NOT NULL,
        "CreatedAt" timestamptz NOT NULL,
        "CreatedBy" bigint NOT NULL,
        "UpdatedAt" timestamptz,
        "UpdatedBy" bigint,
        "DeletedAt" timestamptz,
        "DeletedBy" bigint,
        "IsDeleted" boolean NOT NULL,
        "Version" bigint NOT NULL,
        CONSTRAINT "PK_ChallengeNotices" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM fundex_integration."__EFMigrationsHistory" WHERE "MigrationId" = '20260930195238_CompleteTradingLifecycle') THEN
    CREATE TABLE myfund_prod_trading."Positions" (
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "PositionId" uuid NOT NULL,
        "AccountId" uuid NOT NULL,
        "InstrumentToken" text NOT NULL,
        "Symbol" text NOT NULL,
        "Quantity" numeric(20,4) NOT NULL,
        "ReservedQuantity" numeric(20,4) NOT NULL,
        "AverageCost" numeric(28,10) NOT NULL,
        "LastPrice" numeric(20,4) NOT NULL,
        "RealizedPnl" numeric(20,4) NOT NULL,
        "CreatedAt" timestamptz NOT NULL,
        "CreatedBy" bigint NOT NULL,
        "UpdatedAt" timestamptz,
        "UpdatedBy" bigint,
        "DeletedAt" timestamptz,
        "DeletedBy" bigint,
        "IsDeleted" boolean NOT NULL,
        "Version" bigint NOT NULL,
        CONSTRAINT "PK_Positions" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM fundex_integration."__EFMigrationsHistory" WHERE "MigrationId" = '20260930195238_CompleteTradingLifecycle') THEN
    CREATE TABLE myfund_sandbox_trading."Positions" (
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "PositionId" uuid NOT NULL,
        "AccountId" uuid NOT NULL,
        "InstrumentToken" text NOT NULL,
        "Symbol" text NOT NULL,
        "ReservedQuantity" numeric(20,4) NOT NULL,
        "Quantity" numeric(20,4) NOT NULL,
        "AverageCost" numeric(28,10) NOT NULL,
        "LastPrice" numeric(20,4) NOT NULL,
        "RealizedPnl" numeric(20,4) NOT NULL,
        "CreatedAt" timestamptz NOT NULL,
        "CreatedBy" bigint NOT NULL,
        "UpdatedAt" timestamptz,
        "UpdatedBy" bigint,
        "DeletedAt" timestamptz,
        "DeletedBy" bigint,
        "IsDeleted" boolean NOT NULL,
        "Version" bigint NOT NULL,
        CONSTRAINT "PK_Positions" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM fundex_integration."__EFMigrationsHistory" WHERE "MigrationId" = '20260930195238_CompleteTradingLifecycle') THEN
    CREATE TABLE myfund_prod_trading."ProfitDistributions" (
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "DistributionId" uuid NOT NULL,
        "AccountId" uuid NOT NULL,
        "AccountInternalId" bigint NOT NULL,
        "SettlementReference" text NOT NULL,
        "GrossProfit" numeric(20,4) NOT NULL,
        "Fees" numeric(20,4) NOT NULL,
        "TraderReward" numeric(20,4) NOT NULL,
        "PlatformReward" numeric(20,4) NOT NULL,
        "DeliveredAt" timestamp with time zone,
        "CreatedAt" timestamptz NOT NULL,
        "CreatedBy" bigint NOT NULL,
        "UpdatedAt" timestamptz,
        "UpdatedBy" bigint,
        "DeletedAt" timestamptz,
        "DeletedBy" bigint,
        "IsDeleted" boolean NOT NULL,
        "Version" bigint NOT NULL,
        CONSTRAINT "PK_ProfitDistributions" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM fundex_integration."__EFMigrationsHistory" WHERE "MigrationId" = '20260930195238_CompleteTradingLifecycle') THEN
    CREATE TABLE myfund_prod_wallet."WithdrawalHolds" (
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "WithdrawalId" uuid NOT NULL,
        "WalletInternalId" bigint NOT NULL,
        "Amount" numeric(20,4) NOT NULL,
        "Status" text NOT NULL,
        "CreatedAt" timestamptz NOT NULL,
        "CreatedBy" bigint NOT NULL,
        "UpdatedAt" timestamptz,
        "UpdatedBy" bigint,
        "DeletedAt" timestamptz,
        "DeletedBy" bigint,
        "IsDeleted" boolean NOT NULL,
        "Version" bigint NOT NULL,
        CONSTRAINT "PK_WithdrawalHolds" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM fundex_integration."__EFMigrationsHistory" WHERE "MigrationId" = '20260930195238_CompleteTradingLifecycle') THEN
    CREATE UNIQUE INDEX "IX_Requests_ProviderPayoutId" ON fundex_withdrawal."Requests" ("ProviderPayoutId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM fundex_integration."__EFMigrationsHistory" WHERE "MigrationId" = '20260930195238_CompleteTradingLifecycle') THEN
    CREATE INDEX "IX_Requests_Status_Id" ON fundex_withdrawal."Requests" ("Status", "Id");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM fundex_integration."__EFMigrationsHistory" WHERE "MigrationId" = '20260930195238_CompleteTradingLifecycle') THEN
    CREATE UNIQUE INDEX "IX_Executions_OrderInternalId_BrokerExecutionId" ON fundex_trading."Executions" ("OrderInternalId", "BrokerExecutionId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM fundex_integration."__EFMigrationsHistory" WHERE "MigrationId" = '20260930195238_CompleteTradingLifecycle') THEN
    CREATE INDEX "IX_Entries_TransactionInternalId" ON fundex_wallet."Entries" ("TransactionInternalId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM fundex_integration."__EFMigrationsHistory" WHERE "MigrationId" = '20260930195238_CompleteTradingLifecycle') THEN
    CREATE UNIQUE INDEX "IX_Accounts_BrokerProvider_BrokerUserId" ON fundex_accounts."Accounts" ("BrokerProvider", "BrokerUserId") WHERE "BrokerUserId" IS NOT NULL;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM fundex_integration."__EFMigrationsHistory" WHERE "MigrationId" = '20260930195238_CompleteTradingLifecycle') THEN
    CREATE UNIQUE INDEX "IX_Books_AccountId" ON myfund_prod_trading."Books" ("AccountId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM fundex_integration."__EFMigrationsHistory" WHERE "MigrationId" = '20260930195238_CompleteTradingLifecycle') THEN
    CREATE UNIQUE INDEX "IX_Books_AccountId1" ON myfund_sandbox_trading."Books" ("AccountId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM fundex_integration."__EFMigrationsHistory" WHERE "MigrationId" = '20260930195238_CompleteTradingLifecycle') THEN
    CREATE INDEX "IX_ChallengeNotices_DeliveredAt_LeaseUntil" ON fundex_subscription."ChallengeNotices" ("DeliveredAt", "LeaseUntil");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM fundex_integration."__EFMigrationsHistory" WHERE "MigrationId" = '20260930195238_CompleteTradingLifecycle') THEN
    CREATE UNIQUE INDEX "IX_ChallengeNotices_SubscriptionInternalId_Outcome" ON fundex_subscription."ChallengeNotices" ("SubscriptionInternalId", "Outcome");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM fundex_integration."__EFMigrationsHistory" WHERE "MigrationId" = '20260930195238_CompleteTradingLifecycle') THEN
    CREATE UNIQUE INDEX "IX_Positions_AccountId_InstrumentToken" ON myfund_prod_trading."Positions" ("AccountId", "InstrumentToken");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM fundex_integration."__EFMigrationsHistory" WHERE "MigrationId" = '20260930195238_CompleteTradingLifecycle') THEN
    CREATE UNIQUE INDEX "IX_Positions_AccountId_InstrumentToken1" ON myfund_sandbox_trading."Positions" ("AccountId", "InstrumentToken");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM fundex_integration."__EFMigrationsHistory" WHERE "MigrationId" = '20260930195238_CompleteTradingLifecycle') THEN
    CREATE UNIQUE INDEX "IX_ProfitDistributions_AccountId_SettlementReference" ON myfund_prod_trading."ProfitDistributions" ("AccountId", "SettlementReference");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM fundex_integration."__EFMigrationsHistory" WHERE "MigrationId" = '20260930195238_CompleteTradingLifecycle') THEN
    CREATE UNIQUE INDEX "IX_ProfitDistributions_DistributionId" ON myfund_prod_trading."ProfitDistributions" ("DistributionId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM fundex_integration."__EFMigrationsHistory" WHERE "MigrationId" = '20260930195238_CompleteTradingLifecycle') THEN
    CREATE UNIQUE INDEX "IX_WithdrawalHolds_WithdrawalId" ON myfund_prod_wallet."WithdrawalHolds" ("WithdrawalId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM fundex_integration."__EFMigrationsHistory" WHERE "MigrationId" = '20260930195238_CompleteTradingLifecycle') THEN
    ALTER TABLE fundex_wallet."Entries" ADD CONSTRAINT "FK_Entries_Transactions_TransactionInternalId" FOREIGN KEY ("TransactionInternalId") REFERENCES fundex_wallet."Transactions" ("Id") ON DELETE RESTRICT;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM fundex_integration."__EFMigrationsHistory" WHERE "MigrationId" = '20260930195238_CompleteTradingLifecycle') THEN
    ALTER TABLE fundex_trading."Executions" ADD CONSTRAINT "FK_Executions_Orders_OrderInternalId" FOREIGN KEY ("OrderInternalId") REFERENCES fundex_trading."Orders" ("Id") ON DELETE RESTRICT;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM fundex_integration."__EFMigrationsHistory" WHERE "MigrationId" = '20260930195238_CompleteTradingLifecycle') THEN
    INSERT INTO fundex_integration."__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260930195238_CompleteTradingLifecycle', '8.0.10');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM fundex_integration."__EFMigrationsHistory" WHERE "MigrationId" = '20260930195650_ScheduleWithdrawalPolling') THEN
    ALTER TABLE fundex_withdrawal."Requests" ADD "NextCheckAt" timestamp with time zone;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM fundex_integration."__EFMigrationsHistory" WHERE "MigrationId" = '20260930195650_ScheduleWithdrawalPolling') THEN
    CREATE INDEX "IX_Requests_Status_NextCheckAt" ON fundex_withdrawal."Requests" ("Status", "NextCheckAt");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM fundex_integration."__EFMigrationsHistory" WHERE "MigrationId" = '20260930195650_ScheduleWithdrawalPolling') THEN
    INSERT INTO fundex_integration."__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260930195650_ScheduleWithdrawalPolling', '8.0.10');
    END IF;
END $EF$;
COMMIT;

