START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM fundex_integration."__EFMigrationsHistory" WHERE "MigrationId" = '20261001035910_StandardizeSchemasAndIdentity') THEN
    ALTER SCHEMA myfund_prod_trading RENAME TO fundex_prod_trading;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM fundex_integration."__EFMigrationsHistory" WHERE "MigrationId" = '20261001035910_StandardizeSchemasAndIdentity') THEN
    ALTER SCHEMA myfund_sandbox_trading RENAME TO fundex_sandbox_trading;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM fundex_integration."__EFMigrationsHistory" WHERE "MigrationId" = '20261001035910_StandardizeSchemasAndIdentity') THEN
    ALTER SCHEMA myfund_prod_wallet RENAME TO fundex_prod_wallet;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM fundex_integration."__EFMigrationsHistory" WHERE "MigrationId" = '20261001035910_StandardizeSchemasAndIdentity') THEN
    ALTER TABLE fundex_identity."Users" ADD "SecurityVersion" bigint NOT NULL DEFAULT 1;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM fundex_integration."__EFMigrationsHistory" WHERE "MigrationId" = '20261001035910_StandardizeSchemasAndIdentity') THEN
    CREATE TABLE fundex_identity."IdentityEvents" (
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "EventId" uuid NOT NULL,
        "UserInternalId" bigint,
        "EventType" character varying(60) NOT NULL,
        "Method" character varying(30) NOT NULL,
        "Succeeded" boolean NOT NULL,
        "Detail" character varying(500),
        "CreatedAt" timestamptz NOT NULL,
        "CreatedBy" bigint NOT NULL,
        "UpdatedAt" timestamptz,
        "UpdatedBy" bigint,
        "DeletedAt" timestamptz,
        "DeletedBy" bigint,
        "IsDeleted" boolean NOT NULL,
        "Version" bigint NOT NULL,
        CONSTRAINT "PK_IdentityEvents" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_IdentityEvents_Users_UserInternalId" FOREIGN KEY ("UserInternalId") REFERENCES fundex_identity."Users" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM fundex_integration."__EFMigrationsHistory" WHERE "MigrationId" = '20261001035910_StandardizeSchemasAndIdentity') THEN
    CREATE INDEX "IX_UserRoles_RoleInternalId" ON fundex_identity."UserRoles" ("RoleInternalId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM fundex_integration."__EFMigrationsHistory" WHERE "MigrationId" = '20261001035910_StandardizeSchemasAndIdentity') THEN
    CREATE UNIQUE INDEX "IX_UserRoles_UserInternalId_RoleInternalId" ON fundex_identity."UserRoles" ("UserInternalId", "RoleInternalId") WHERE "IsDeleted" = false;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM fundex_integration."__EFMigrationsHistory" WHERE "MigrationId" = '20261001035910_StandardizeSchemasAndIdentity') THEN
    CREATE UNIQUE INDEX "IX_Roles_RoleId" ON fundex_identity."Roles" ("RoleId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM fundex_integration."__EFMigrationsHistory" WHERE "MigrationId" = '20261001035910_StandardizeSchemasAndIdentity') THEN
    CREATE INDEX "IX_RolePermissions_PermissionInternalId" ON fundex_identity."RolePermissions" ("PermissionInternalId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM fundex_integration."__EFMigrationsHistory" WHERE "MigrationId" = '20261001035910_StandardizeSchemasAndIdentity') THEN
    CREATE UNIQUE INDEX "IX_RolePermissions_RoleInternalId_PermissionInternalId" ON fundex_identity."RolePermissions" ("RoleInternalId", "PermissionInternalId") WHERE "IsDeleted" = false;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM fundex_integration."__EFMigrationsHistory" WHERE "MigrationId" = '20261001035910_StandardizeSchemasAndIdentity') THEN
    CREATE UNIQUE INDEX "IX_Permissions_PermissionId" ON fundex_identity."Permissions" ("PermissionId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM fundex_integration."__EFMigrationsHistory" WHERE "MigrationId" = '20261001035910_StandardizeSchemasAndIdentity') THEN
    CREATE UNIQUE INDEX "IX_IdentityEvents_EventId" ON fundex_identity."IdentityEvents" ("EventId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM fundex_integration."__EFMigrationsHistory" WHERE "MigrationId" = '20261001035910_StandardizeSchemasAndIdentity') THEN
    CREATE INDEX "IX_IdentityEvents_UserInternalId_CreatedAt" ON fundex_identity."IdentityEvents" ("UserInternalId", "CreatedAt");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM fundex_integration."__EFMigrationsHistory" WHERE "MigrationId" = '20261001035910_StandardizeSchemasAndIdentity') THEN
    ALTER TABLE fundex_identity."RolePermissions" ADD CONSTRAINT "FK_RolePermissions_Permissions_PermissionInternalId" FOREIGN KEY ("PermissionInternalId") REFERENCES fundex_identity."Permissions" ("Id") ON DELETE RESTRICT;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM fundex_integration."__EFMigrationsHistory" WHERE "MigrationId" = '20261001035910_StandardizeSchemasAndIdentity') THEN
    ALTER TABLE fundex_identity."RolePermissions" ADD CONSTRAINT "FK_RolePermissions_Roles_RoleInternalId" FOREIGN KEY ("RoleInternalId") REFERENCES fundex_identity."Roles" ("Id") ON DELETE RESTRICT;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM fundex_integration."__EFMigrationsHistory" WHERE "MigrationId" = '20261001035910_StandardizeSchemasAndIdentity') THEN
    ALTER TABLE fundex_identity."UserRoles" ADD CONSTRAINT "FK_UserRoles_Roles_RoleInternalId" FOREIGN KEY ("RoleInternalId") REFERENCES fundex_identity."Roles" ("Id") ON DELETE RESTRICT;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM fundex_integration."__EFMigrationsHistory" WHERE "MigrationId" = '20261001035910_StandardizeSchemasAndIdentity') THEN
    ALTER TABLE fundex_identity."UserRoles" ADD CONSTRAINT "FK_UserRoles_Users_UserInternalId" FOREIGN KEY ("UserInternalId") REFERENCES fundex_identity."Users" ("Id") ON DELETE RESTRICT;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM fundex_integration."__EFMigrationsHistory" WHERE "MigrationId" = '20261001035910_StandardizeSchemasAndIdentity') THEN
    INSERT INTO fundex_identity."Roles" ("RoleId", "Code", "Name", "CreatedAt", "CreatedBy", "IsDeleted", "Version")
    SELECT gen_random_uuid(), role.code, role.name, now(), 0, false, 1
    FROM (VALUES ('TRADER', 'Trader'), ('MANAGER', 'Manager'), ('ADMIN', 'Administrator')) AS role(code,name)
    WHERE NOT EXISTS (SELECT 1 FROM fundex_identity."Roles" existing WHERE existing."Code" = role.code AND NOT existing."IsDeleted");

    INSERT INTO fundex_identity."UserRoles" ("UserInternalId", "RoleInternalId", "CreatedAt", "CreatedBy", "IsDeleted", "Version")
    SELECT member."Id", role."Id", now(), 0, false, 1
    FROM fundex_identity."Users" member
    JOIN fundex_identity."Roles" role ON role."Code" = 'TRADER' AND NOT role."IsDeleted"
    WHERE NOT member."IsDeleted" AND NOT EXISTS
      (SELECT 1 FROM fundex_identity."UserRoles" link WHERE link."UserInternalId" = member."Id" AND NOT link."IsDeleted");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM fundex_integration."__EFMigrationsHistory" WHERE "MigrationId" = '20261001035910_StandardizeSchemasAndIdentity') THEN
    INSERT INTO fundex_integration."__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20261001035910_StandardizeSchemasAndIdentity', '8.0.10');
    END IF;
END $EF$;
COMMIT;

