START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM fundex_integration."__EFMigrationsHistory" WHERE "MigrationId" = '20261002113846_BusinessManagement') THEN
        IF NOT EXISTS(SELECT 1 FROM pg_namespace WHERE nspname = 'fundex_administration') THEN
            CREATE SCHEMA fundex_administration;
        END IF;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM fundex_integration."__EFMigrationsHistory" WHERE "MigrationId" = '20261002113846_BusinessManagement') THEN
    ALTER TABLE fundex_payments."Payments" ADD "CouponCode" text;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM fundex_integration."__EFMigrationsHistory" WHERE "MigrationId" = '20261002113846_BusinessManagement') THEN
    ALTER TABLE fundex_payments."Payments" ADD "CouponId" uuid;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM fundex_integration."__EFMigrationsHistory" WHERE "MigrationId" = '20261002113846_BusinessManagement') THEN
    ALTER TABLE fundex_payments."Payments" ADD "DiscountAmount" numeric(20,4) NOT NULL DEFAULT 0.0;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM fundex_integration."__EFMigrationsHistory" WHERE "MigrationId" = '20261002113846_BusinessManagement') THEN
    ALTER TABLE fundex_payments."Payments" ADD "OriginalAmount" numeric(20,4) NOT NULL DEFAULT 0.0;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM fundex_integration."__EFMigrationsHistory" WHERE "MigrationId" = '20261002113846_BusinessManagement') THEN
    CREATE TABLE fundex_administration."AudienceMembers" (
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "MemberId" uuid NOT NULL,
        "AudienceId" uuid NOT NULL,
        "Email" text NOT NULL,
        "Name" text NOT NULL,
        "MarketingConsent" boolean NOT NULL,
        "ConsentSource" text NOT NULL,
        "ConsentedAt" timestamp with time zone,
        "UnsubscribedAt" timestamp with time zone,
        "UnsubscribeToken" uuid NOT NULL,
        "CreatedAt" timestamptz NOT NULL,
        "CreatedBy" bigint NOT NULL,
        "UpdatedAt" timestamptz,
        "UpdatedBy" bigint,
        "DeletedAt" timestamptz,
        "DeletedBy" bigint,
        "IsDeleted" boolean NOT NULL,
        "Version" bigint NOT NULL,
        CONSTRAINT "PK_AudienceMembers" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM fundex_integration."__EFMigrationsHistory" WHERE "MigrationId" = '20261002113846_BusinessManagement') THEN
    CREATE TABLE fundex_administration."Audiences" (
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "AudienceId" uuid NOT NULL,
        "Name" text NOT NULL,
        "Description" text NOT NULL,
        "CreatedAt" timestamptz NOT NULL,
        "CreatedBy" bigint NOT NULL,
        "UpdatedAt" timestamptz,
        "UpdatedBy" bigint,
        "DeletedAt" timestamptz,
        "DeletedBy" bigint,
        "IsDeleted" boolean NOT NULL,
        "Version" bigint NOT NULL,
        CONSTRAINT "PK_Audiences" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM fundex_integration."__EFMigrationsHistory" WHERE "MigrationId" = '20261002113846_BusinessManagement') THEN
    CREATE TABLE fundex_administration."CampaignDeliveries" (
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "DeliveryId" uuid NOT NULL,
        "CampaignId" uuid NOT NULL,
        "MemberId" uuid NOT NULL,
        "Email" text NOT NULL,
        "Status" text NOT NULL,
        "Attempts" integer NOT NULL,
        "LeaseUntil" timestamp with time zone,
        "SentAt" timestamp with time zone,
        "Error" text,
        "CreatedAt" timestamptz NOT NULL,
        "CreatedBy" bigint NOT NULL,
        "UpdatedAt" timestamptz,
        "UpdatedBy" bigint,
        "DeletedAt" timestamptz,
        "DeletedBy" bigint,
        "IsDeleted" boolean NOT NULL,
        "Version" bigint NOT NULL,
        CONSTRAINT "PK_CampaignDeliveries" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM fundex_integration."__EFMigrationsHistory" WHERE "MigrationId" = '20261002113846_BusinessManagement') THEN
    CREATE TABLE fundex_administration."Campaigns" (
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "CampaignId" uuid NOT NULL,
        "AudienceId" uuid NOT NULL,
        "Name" text NOT NULL,
        "Subject" text NOT NULL,
        "Body" text NOT NULL,
        "Status" text NOT NULL,
        "ScheduledAt" timestamp with time zone,
        "QueuedAt" timestamp with time zone,
        "CreatedAt" timestamptz NOT NULL,
        "CreatedBy" bigint NOT NULL,
        "UpdatedAt" timestamptz,
        "UpdatedBy" bigint,
        "DeletedAt" timestamptz,
        "DeletedBy" bigint,
        "IsDeleted" boolean NOT NULL,
        "Version" bigint NOT NULL,
        CONSTRAINT "PK_Campaigns" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM fundex_integration."__EFMigrationsHistory" WHERE "MigrationId" = '20261002113846_BusinessManagement') THEN
    CREATE TABLE fundex_administration."ContentEntries" (
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "ContentId" uuid NOT NULL,
        "Kind" text NOT NULL,
        "Slug" text NOT NULL,
        "Title" text NOT NULL,
        "Body" text NOT NULL,
        "Status" text NOT NULL,
        "StartsAt" timestamp with time zone,
        "EndsAt" timestamp with time zone,
        "CreatedAt" timestamptz NOT NULL,
        "CreatedBy" bigint NOT NULL,
        "UpdatedAt" timestamptz,
        "UpdatedBy" bigint,
        "DeletedAt" timestamptz,
        "DeletedBy" bigint,
        "IsDeleted" boolean NOT NULL,
        "Version" bigint NOT NULL,
        CONSTRAINT "PK_ContentEntries" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM fundex_integration."__EFMigrationsHistory" WHERE "MigrationId" = '20261002113846_BusinessManagement') THEN
    CREATE TABLE fundex_payments."Coupons" (
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "CouponId" uuid NOT NULL,
        "Code" character varying(40) NOT NULL,
        "Name" character varying(150) NOT NULL,
        "DiscountType" text NOT NULL,
        "Value" numeric(20,4) NOT NULL,
        "MinimumFee" numeric(20,4) NOT NULL,
        "PlanId" uuid,
        "UserId" uuid,
        "StartsAt" timestamp with time zone NOT NULL,
        "EndsAt" timestamp with time zone NOT NULL,
        "MaximumUses" integer NOT NULL,
        "UsesPerUser" integer NOT NULL,
        "ReservedUses" integer NOT NULL,
        "IsActive" boolean NOT NULL,
        "CreatedAt" timestamptz NOT NULL,
        "CreatedBy" bigint NOT NULL,
        "UpdatedAt" timestamptz,
        "UpdatedBy" bigint,
        "DeletedAt" timestamptz,
        "DeletedBy" bigint,
        "IsDeleted" boolean NOT NULL,
        "Version" bigint NOT NULL,
        CONSTRAINT "PK_Coupons" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM fundex_integration."__EFMigrationsHistory" WHERE "MigrationId" = '20261002113846_BusinessManagement') THEN
    CREATE INDEX "IX_Payments_CouponId_UserInternalId" ON fundex_payments."Payments" ("CouponId", "UserInternalId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM fundex_integration."__EFMigrationsHistory" WHERE "MigrationId" = '20261002113846_BusinessManagement') THEN
    CREATE UNIQUE INDEX "IX_AudienceMembers_AudienceId_Email" ON fundex_administration."AudienceMembers" ("AudienceId", "Email");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM fundex_integration."__EFMigrationsHistory" WHERE "MigrationId" = '20261002113846_BusinessManagement') THEN
    CREATE UNIQUE INDEX "IX_AudienceMembers_MemberId" ON fundex_administration."AudienceMembers" ("MemberId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM fundex_integration."__EFMigrationsHistory" WHERE "MigrationId" = '20261002113846_BusinessManagement') THEN
    CREATE UNIQUE INDEX "IX_AudienceMembers_UnsubscribeToken" ON fundex_administration."AudienceMembers" ("UnsubscribeToken");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM fundex_integration."__EFMigrationsHistory" WHERE "MigrationId" = '20261002113846_BusinessManagement') THEN
    CREATE UNIQUE INDEX "IX_Audiences_AudienceId" ON fundex_administration."Audiences" ("AudienceId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM fundex_integration."__EFMigrationsHistory" WHERE "MigrationId" = '20261002113846_BusinessManagement') THEN
    CREATE UNIQUE INDEX "IX_CampaignDeliveries_CampaignId_MemberId" ON fundex_administration."CampaignDeliveries" ("CampaignId", "MemberId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM fundex_integration."__EFMigrationsHistory" WHERE "MigrationId" = '20261002113846_BusinessManagement') THEN
    CREATE UNIQUE INDEX "IX_CampaignDeliveries_DeliveryId" ON fundex_administration."CampaignDeliveries" ("DeliveryId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM fundex_integration."__EFMigrationsHistory" WHERE "MigrationId" = '20261002113846_BusinessManagement') THEN
    CREATE INDEX "IX_CampaignDeliveries_Status_LeaseUntil" ON fundex_administration."CampaignDeliveries" ("Status", "LeaseUntil");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM fundex_integration."__EFMigrationsHistory" WHERE "MigrationId" = '20261002113846_BusinessManagement') THEN
    CREATE UNIQUE INDEX "IX_Campaigns_CampaignId" ON fundex_administration."Campaigns" ("CampaignId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM fundex_integration."__EFMigrationsHistory" WHERE "MigrationId" = '20261002113846_BusinessManagement') THEN
    CREATE UNIQUE INDEX "IX_ContentEntries_ContentId" ON fundex_administration."ContentEntries" ("ContentId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM fundex_integration."__EFMigrationsHistory" WHERE "MigrationId" = '20261002113846_BusinessManagement') THEN
    CREATE UNIQUE INDEX "IX_ContentEntries_Slug" ON fundex_administration."ContentEntries" ("Slug");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM fundex_integration."__EFMigrationsHistory" WHERE "MigrationId" = '20261002113846_BusinessManagement') THEN
    CREATE UNIQUE INDEX "IX_Coupons_Code" ON fundex_payments."Coupons" ("Code");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM fundex_integration."__EFMigrationsHistory" WHERE "MigrationId" = '20261002113846_BusinessManagement') THEN
    CREATE UNIQUE INDEX "IX_Coupons_CouponId" ON fundex_payments."Coupons" ("CouponId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM fundex_integration."__EFMigrationsHistory" WHERE "MigrationId" = '20261002113846_BusinessManagement') THEN
    INSERT INTO fundex_integration."__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20261002113846_BusinessManagement', '8.0.10');
    END IF;
END $EF$;
COMMIT;

