<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="..\MyFundex.BuildingBlocks\MyFundex.BuildingBlocks.csproj" />
    <ProjectReference Include="..\MyFundex.Contracts\MyFundex.Contracts.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.10" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="8.0.8" />

  </ItemGroup>
</Project>