using Microsoft.EntityFrameworkCore;using Microsoft.Extensions.DependencyInjection;using MyFundex.BuildingBlocks.Abstractions;using MyFundex.BuildingBlocks.Domain;using MyFundex.BuildingBlocks.Persistence;using MyFundex.Contracts;
namespace MyFundex.Risk;
public sealed class PolicySet:EntityBase{public Guid PolicyId{get;set;}public string Code{get;set;}="";public string Name{get;set;}="";public string PolicyType{get;set;}="Trading";}
public sealed class PolicyVersion:EntityBase{public Guid PolicyVersionId{get;set;}public long PolicySetInternalId{get;set;}public int VersionNumber{get;set;}public string Status{get;set;}="Draft";public DateTimeOffset EffectiveFrom{get;set;}public DateTimeOffset? EffectiveTo{get;set;}public string ApplicationMode{get;set;}="NextTrade";}
public sealed class PolicyRule:EntityBase{public Guid RuleId{get;set;}public long PolicyVersionInternalId{get;set;}public string RuleCode{get;set;}="";public string Name{get;set;}="";public string Category{get;set;}="Trading";public string Operator{get;set;}="GreaterThan";public string ViolationAction{get;set;}="RejectOrder";public int Priority{get;set;}public bool IsEnabled{get;set;}=true;public decimal? DecimalValue{get;set;}public int? IntegerValue{get;set;}public string? StringValue{get;set;}}
public sealed class PolicyAssignment:EntityBase{public Guid AssignmentId{get;set;}public long FundedAccountInternalId{get;set;}public long PolicyVersionInternalId{get;set;}public DateTimeOffset EffectiveFrom{get;set;}public DateTimeOffset? EffectiveTo{get;set;}}
public sealed class PolicyViolation:EntityBase{public Guid ViolationId{get;set;}public long FundedAccountInternalId{get;set;}public long PolicyRuleInternalId{get;set;}public string? ObservedValue{get;set;}public string? LimitValue{get;set;}public string ActionTaken{get;set;}="";public DateTimeOffset OccurredAt{get;set;}}
public sealed class RiskDbContext(DbContextOptions<RiskDbContext> o,ICurrentActor a):AuditableDbContext(o,a){public DbSet<PolicySet>PolicySets=>Set<PolicySet>();public DbSet<PolicyVersion>PolicyVersions=>Set<PolicyVersion>();public DbSet<PolicyRule>Rules=>Set<PolicyRule>();public DbSet<PolicyAssignment>Assignments=>Set<PolicyAssignment>();public DbSet<PolicyViolation>Violations=>Set<PolicyViolation>();protected override void OnModelCreating(ModelBuilder m){m.HasDefaultSchema("risk");ConfigureEntity(m.Entity<PolicySet>());ConfigureEntity(m.Entity<PolicyVersion>());ConfigureEntity(m.Entity<PolicyRule>());ConfigureEntity(m.Entity<PolicyAssignment>());ConfigureEntity(m.Entity<PolicyViolation>());m.Entity<PolicySet>().HasIndex(x=>x.PolicyId).IsUnique();m.Entity<PolicySet>().HasIndex(x=>x.Code).IsUnique().HasFilter("is_deleted=false");m.Entity<PolicyRule>().Property(x=>x.DecimalValue).HasPrecision(20,6);}}
public sealed class RiskGuard(RiskDbContext db):IRiskGuard{
 public async Task<RiskCheckResult> EvaluateAsync(RiskCheckRequest r,CancellationToken ct){var rules=await (from a in db.Assignments.AsNoTracking() join v in db.PolicyVersions.AsNoTracking() on a.PolicyVersionInternalId equals v.Id join x in db.Rules.AsNoTracking() on v.Id equals x.PolicyVersionInternalId where a.FundedAccountInternalId==r.AccountInternalId&&x.IsEnabled&&v.Status=="Active" orderby x.Priority select x).ToListAsync(ct);foreach(var x in rules){if(x.RuleCode=="MAX_ORDER_VALUE"&&x.DecimalValue.HasValue&&r.EstimatedValue>x.DecimalValue.Value)return new(false,x.RuleCode,$"Order value exceeds {x.DecimalValue.Value}");if(x.RuleCode=="EQUITY_ONLY"&&!r.InstrumentToken.StartsWith("NSE_EQ|",StringComparison.OrdinalIgnoreCase))return new(false,x.RuleCode,"Only NSE equity instruments are allowed.");}return new(true);}
}
public static class RiskModule{public static IServiceCollection AddRiskModule(this IServiceCollection s,string cs){s.AddDbContext<RiskDbContext>(o=>o.UseNpgsql(cs));s.AddScoped<IRiskGuard,RiskGuard>();return s;}}
