using Microsoft.EntityFrameworkCore; using Microsoft.Extensions.Caching.Memory; using Microsoft.Extensions.DependencyInjection; using MyFundex.BuildingBlocks.Abstractions; using MyFundex.BuildingBlocks.Domain; using MyFundex.BuildingBlocks.Persistence;using MyFundex.Contracts;
namespace MyFundex.Configuration;
public sealed class SystemSetting:EntityBase{public Guid SettingId{get;set;} public string SettingKey{get;set;}=""; public string SettingValue{get;set;}=""; public string ValueType{get;set;}="String"; public string Category{get;set;}="General"; public string Environment{get;set;}="UAT"; public bool IsSensitive{get;set;} public string? Description{get;set;}}
public sealed class ConfigurationDbContext(DbContextOptions<ConfigurationDbContext> o,ICurrentActor a):AuditableDbContext(o,a){public DbSet<SystemSetting>Settings=>Set<SystemSetting>();protected override void OnModelCreating(ModelBuilder m){m.HasDefaultSchema("configuration");ConfigureEntity(m.Entity<SystemSetting>());m.Entity<SystemSetting>().HasIndex(x=>new{x.SettingKey,x.Environment}).IsUnique().HasFilter("is_deleted=false");}}
public sealed class RuntimeSettings(ConfigurationDbContext db,IMemoryCache cache):IRuntimeSettings{
 public async Task<string?> GetAsync(string key,string env,CancellationToken ct){var ck=$"cfg:{env}:{key}";if(cache.TryGetValue<string>(ck,out var v))return v;v=await db.Settings.AsNoTracking().Where(x=>x.SettingKey==key&&x.Environment==env).Select(x=>x.SettingValue).SingleOrDefaultAsync(ct);if(v!=null)cache.Set(ck,v,TimeSpan.FromMinutes(5));return v;}
 public async Task UpsertAsync(string key,string value,string env,string category,long actor,CancellationToken ct){var x=await db.Settings.SingleOrDefaultAsync(s=>s.SettingKey==key&&s.Environment==env,ct);if(x==null){x=new(){SettingId=MyFundex.BuildingBlocks.Ids.Uuid7.NewGuid(),SettingKey=key,SettingValue=value,Environment=env,Category=category};db.Add(x);}else x.SettingValue=value;await db.SaveChangesAsync(ct);cache.Remove($"cfg:{env}:{key}");}
}
public static class ConfigurationModule{public static IServiceCollection AddConfigurationModule(this IServiceCollection s,string cs){s.AddMemoryCache();s.AddDbContext<ConfigurationDbContext>(o=>o.UseNpgsql(cs));s.AddScoped<IRuntimeSettings,RuntimeSettings>();return s;}}
