using System.Net.Http.Headers;using System.Net.Http.Json;using System.Text.Json;using Microsoft.EntityFrameworkCore;using Microsoft.Extensions.DependencyInjection;using MyFundex.BuildingBlocks.Abstractions;using MyFundex.BuildingBlocks.Domain;using MyFundex.BuildingBlocks.Persistence;using MyFundex.Contracts;
namespace MyFundex.Broker;
public sealed class BrokerAccount:EntityBase{public Guid BrokerAccountId{get;set;}public string ProviderCode{get;set;}="UPSTOX";public string Environment{get;set;}="SANDBOX";public string AccountReference{get;set;}="";public bool IsActive{get;set;}=true;}
public sealed class BrokerEvent:EntityBase{public Guid BrokerEventId{get;set;}public string Provider{get;set;}="UPSTOX";public string Environment{get;set;}="SANDBOX";public string EventType{get;set;}="";public string? ProviderOrderId{get;set;}public string Payload{get;set;}="";public DateTimeOffset ReceivedAt{get;set;}=DateTimeOffset.UtcNow;}
public sealed class BrokerDbContext(DbContextOptions<BrokerDbContext> o,ICurrentActor a):AuditableDbContext(o,a){public DbSet<BrokerAccount>Accounts=>Set<BrokerAccount>();public DbSet<BrokerEvent>Events=>Set<BrokerEvent>();protected override void OnModelCreating(ModelBuilder m) => ConfigureModel(m); public static void ConfigureModel(ModelBuilder m) {m.HasDefaultSchema("broker");ConfigureEntity(m.Entity<BrokerAccount>());ConfigureEntity(m.Entity<BrokerEvent>());m.Entity<BrokerAccount>().HasIndex(x=>x.BrokerAccountId).IsUnique();m.Entity<BrokerEvent>().HasIndex(x=>x.BrokerEventId).IsUnique();}}
public sealed class UpstoxOrderGateway(HttpClient http,IRuntimeSettings settings):IBrokerOrderGateway{
 public async Task<BrokerOrderResponse> PlaceAsync(BrokerOrderRequest r,CancellationToken ct){var env=(await settings.GetAsync("Broker.Upstox.Environment","GLOBAL",ct)??"SANDBOX").ToUpperInvariant();var token=await settings.GetAsync(env=="PRODUCTION"?"Broker.Upstox.Production.AccessToken":"Broker.Upstox.Sandbox.AccessToken","GLOBAL",ct);if(string.IsNullOrWhiteSpace(token))return new(false,null,"TOKEN_MISSING","Upstox access token is not configured.","");var url=env=="PRODUCTION"?"https://api-hft.upstox.com/v3/order/place":"https://sandbox.upstox.com/v3/order/place";using var req=new HttpRequestMessage(HttpMethod.Post,url);req.Headers.Authorization=new AuthenticationHeaderValue("Bearer",token);req.Headers.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));req.Content=JsonContent.Create(new{quantity=Convert.ToInt32(r.Quantity),product="D",validity="DAY",price=r.Price??0m,tag=r.Tag,instrument_token=r.InstrumentToken,order_type=r.OrderType,transaction_type=r.Side,disclosed_quantity=0,trigger_price=0m,is_amo=false,slice=false});using var resp=await http.SendAsync(req,ct);var raw=await resp.Content.ReadAsStringAsync(ct);string? oid=null;try{using var doc=JsonDocument.Parse(raw);if(doc.RootElement.TryGetProperty("data",out var d)&&d.TryGetProperty("order_ids",out var o)&&o.ValueKind==JsonValueKind.Array&&o.GetArrayLength()==1)oid=o[0].GetString();}catch{}return resp.IsSuccessStatusCode&&!string.IsNullOrWhiteSpace(oid)?new(true,oid,null,null,raw):new(false,null,resp.StatusCode.ToString(),raw,raw);}
}

public sealed class UpstoxMarketQuoteProvider(HttpClient http,IRuntimeSettings settings):IMarketQuoteProvider{
 public async Task<decimal?> GetLtpAsync(string instrumentToken,CancellationToken ct){var token=await settings.GetAsync("Broker.Upstox.MarketData.AccessToken","GLOBAL",ct)??await settings.GetAsync("Broker.Upstox.Production.AccessToken","GLOBAL",ct);if(string.IsNullOrWhiteSpace(token))return null;using var req=new HttpRequestMessage(HttpMethod.Get,"https://api.upstox.com/v3/market-quote/ltp?instrument_key="+Uri.EscapeDataString(instrumentToken));req.Headers.Authorization=new AuthenticationHeaderValue("Bearer",token);req.Headers.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));using var resp=await http.SendAsync(req,ct);if(!resp.IsSuccessStatusCode)return null;using var doc=JsonDocument.Parse(await resp.Content.ReadAsStringAsync(ct));if(!doc.RootElement.TryGetProperty("data",out var data)||data.ValueKind!=JsonValueKind.Object)return null;foreach(var item in data.EnumerateObject()){if(item.Value.TryGetProperty("last_price",out var lp)&&lp.TryGetDecimal(out var price))return price;}return null;}
}

public static class BrokerModule{public static IServiceCollection AddBrokerModule(this IServiceCollection s,string cs){s.AddDbContext<BrokerDbContext>(o=>o.UseNpgsql(cs));s.AddHttpClient<UpstoxOrderGateway>();s.AddHttpClient<UpstoxMarketQuoteProvider>().AddStandardResilienceHandler();s.AddScoped<IBrokerOrderGateway>(sp=>sp.GetRequiredService<UpstoxOrderGateway>());s.AddScoped<IMarketQuoteProvider>(sp=>sp.GetRequiredService<UpstoxMarketQuoteProvider>());return s;}}
